###
# Copyright (c) 2015, Terje Hoås
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright notice,
#     this list of conditions, and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions, and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#   * Neither the name of the author of this software nor the name of
#     contributors to this software may be used to endorse or promote products
#     derived from this software without specific prior written consent.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

###
import datetime

import supybot.utils as utils
from supybot.commands import *
import supybot.plugins as plugins
import supybot.ircutils as ircutils
import supybot.callbacks as callbacks
try:
    from supybot.i18n import PluginInternationalization
    _ = PluginInternationalization('Navnedag')
except ImportError:
    # Placeholder that allows to run the plugin on a bot
    # without the i18n module
    _ = lambda x: x


class Navnedag(callbacks.Plugin):
    """Displays the nameday for the current (or given date) in Norway. In norwegian."""
    pass

    def navnedag(self, irc, msg, args):
        """
        Returnerer info om hvem som har navnedag i dag."""
        now = datetime.datetime.now()
        info = namedata['{0:02}-{1:02}'.format(now.month, now.day)]
        retstr = info[0]
        if (info[1] != ''):
            retstr += '. ' + info[1]
        irc.reply(retstr)
    navnedag = wrap(navnedag)

namedata = {'01-01': ['Jesus[trenger referanse]', '- 1. nyttårsdag, Jesu navnedag'],
    '01-02': ['Dagfinn og Dagfrid', ''],
    '01-03': ['Alfred og Alf', ''],
    '01-04': ['Roar og Roger', ''],
    '01-05': ['Hanna og Hanne', '- Tidligere navnedag for Edvard nå har han 18. mars'],
    '01-06': ['Aslaug og Åslaug', ''],
    '01-07': ['Eldbjørg og Knut', '- 1. etter Eldbjørgdagen (ildbergingsdag) fordi sola snudde, og ilden ikke skulle gjøre skade. 2. etter Knut Lavard, dansk hertug drept denne dagen i 1131'],
    '01-08': ['Turid og Torfinn', '- etter biskop Torfinn av Hamar som døde denne dagen i 1285'],
    '01-09': ['Gunnar og Gunn', ''],
    '01-10': ['Sigmund og Sigrun', ''],
    '01-11': ['Børge og Børre', ''],
    '01-12': ['Reinhard og Reinert', '- Etter Reinhold fra Köln, benediktinermunk som hadde oppsyn med kirkebyggingen, arbeiderne drepte ham i 995 fordi han maste på dem.'],
    '01-13': ['Gisle og Gislaug', ''],
    '01-14': ['Herbjørn og Herbjørg Herborg', 'Herborg ble plusset på i revisjonen fra 1998. Tidligere navnedag for Felix'],
    '01-15': ['Laurits og Laura', ''],
    '01-16': ['Hjalmar og Hilmar', ''],
    '01-17': ['Anton, Tønnes og Tony', '- etter Antonius den store munk og eneboer som først bodde i en brønn og siden bygde det første kristne kloster, død 356'],
    '01-18': ['Hildur og Hild', ''],
    '01-19': ['Marius og Margunn', '- etter perseren Marius som sammen med hustruen Martha ble martyrer i Rom i år 268 fordi de tok seg av fengslede kristne.'],
    '01-20': ['Fabian, Sebastian og Bastian', 'I perioden 1989–1998 var det Lina og Line. Line ble flyttet til 13. mai. Den gamle navnekalenderen fram til 1911 hadde også Fabian og Sebastian. Fabian var pave og ble henrettet med øks i år 250 under Decius\'s forfølgelse, Sebastian var romersk offiser som ble kristen, martyr ca. år 287 under keiser Diokletian'],
    '01-21': ['Agnes og Agnete', '- Sankt Agnes død 304,kyskhetens helgen martyr 13 år gammel, nektet å gifte seg med en hedensk stormann - se Piazza Navona'],
    '01-22': ['Ivan og Vanja', '- tidligere navnedag for Vincent, navnene som er valgt nå ligner kanskje, han er Portugals skytshelgen'],
    '01-23': ['Emil, Emilie og Emma', 'Emilie ble tatt inn i revisjonen fra 1998.'],
    '01-24': ['Joar, Jarle og Jarl', ''],
    '01-25': ['Paul og Pål', '- denne dagen feires i katolsk tradisjon som Paulus\' omvendelsesdag'],
    '01-26': ['Øystein og Esten', '- etter Eystein Erlendsson erkebiskop av Nidaros død 1188'],
    '01-27': ['Gaute, Gurli og Gry', 'Gurli ble tatt inn i revisjonen fra 1998.'],
    '01-28': ['Karl og Karoline', '- Franskekongen Carolus Magnus (Karl den store) døde denne dagen i 814'],
    '01-29': ['Herdis, Hermod og Hermann', 'Hermann ble flyttet hit fra 20. oktober i revisjonen i 1998.'],
    '01-30': ['Gunnhild og Gunda', ''],
    '01-31': ['Idun og Ivar', ''],
    '02-01': ['Birte og Bjarte', '- Katolsk festdag for Brigid av Kildare, irsk skytshelgen død 523'],
    '02-02': ['Jomar og Jostein', ''],
    '02-03': ['Ansgar og Asgeir', '- etter Ansgar, Nordens apostel, død 865 som feires i dag - den katolske kirke i Kristiansand er viet ham'],
    '02-04': ['Veronika og Vera', ''],
    '02-05': ['Agate og Ågot', '- etter Sankt Agatha av Catania død 251 skytshelgen for Spania, Malta og for sykepleiere'],
    '02-06': ['Dortea og Dorte', '- etter den vakre Dorothea, martyr i Lilleasia år 304, hagedyrkernes skytshelgen'],
    '02-07': ['Rikard, Rigmor og Riborg', 'Riborg ble tatt inn i revisjonen fra 1998. Navnedag etter Kong Richard av Wessex dro i 772 på pilegrimsferd til Roma med to sønner, døde i Lucca, Toscana[2]'],
    '02-08': ['Åshild og Åsne', ''],
    '02-09': ['Lone og Leikny', ''],
    '02-10': ['Ingfrid og Ingrid', ''],
    '02-11': ['Ingve og Yngve', ''],
    '02-12': ['Randulf, Randi og Ronja', 'Ronja ble tatt inn i revisjonen fra 1998.'],
    '02-13': ['Svanhild og Svanaug', ''],
    '02-14': ['Hjørdis og Jardar', '#NAVN?'],
    '02-15': ['Sigfred og Sigbjørn', '- etter Sigfrid av England, misjonsbiskop i Sverige død ca. 1045, han kom først til Olav den hellige i Norge.'],
    '02-16': ['Julian, Juliane og Jill', 'Julian ble tatt inn i revisjonen fra 1998. Navnedag etter den hellige Juliana, fødendes skytshelgen, led martyrdøden 305'],
    '02-17': ['Aleksandra, Sandra og Sondre', 'Aleksandra ble tatt inn i revisjonen fra 1998.'],
    '02-18': ['Frøydis og Frode', ''],
    '02-19': ['Ella og Elna', ''],
    '02-20': ['Halldis og Halldor', ''],
    '02-21': ['Samuel, Selma og Celine', 'Celine ble tatt inn i revisjonen fra 1998.'],
    '02-22': ['Tina og Tim', ''],
    '02-23': ['Torstein og Torunn', ''],
    '02-24': ['Mattias, Mattis og Mats', '#NAVN?'],
    '02-25': ['Viktor og Viktoria', '- etter den hellige Victorin, prest i Korint som på 200-tallet flyktet til Egypt, brent under keiser Numerianus'],
    '02-26': ['Inger og Ingjerd', '- etter den hellige Inger, den frankiske prinsessen Ingundis (567-585), datter av kong Sigebert av Austrasia'],
    '02-27': ['Laila og Lill', ''],
    '02-28': ['Marina og Maren', ''],
    '02-29': [' Ingen navnedag, tidligere navnedag for Leander'],
    '03-01': ['Audny og Audun', ''],
    '03-02': ['Erna og Ernst', ''],
    '03-03': ['Gunnbjørg og Gunnveig', '- navnene valgt etter minnedagen for Kunigunde av Luxemburg, gift med Henrik av Bayern, skytshelgen for syke barn og gravide, død 1033'],
    '03-04': ['Ada og Adrian', 'Adrian ble tatt inn i revisjonen fra 1998, og Odd ble flyttet til 15. april. Navnedagen er etter både Pave Hadrian som ble martyr år 304 - og etter Adrian prins av Ungarn som ble biskop i Skottland, drept 888.'],
    '03-05': ['Patrick og Patricia', 'Patricia ble tatt inn i revisjonen fra 1998. Men St.Patrick\'s dag blir feiret 17.mars og er Irland\'s nasjonaldag.'],
    '03-06': ['Annfrid og Andor', ''],
    '03-07': ['Arild og Are', ''],
    '03-08': ['Beate, Betty og Bettina', 'Bettina ble tatt inn i revisjonen fra 1998. Navnedagen er etter den hellige Beata av Sens, som kom sammen med biskop Gyril til Frankrike, ble halshugd i 273, feires nå 6.sept i katolsk tradisjon.'],
    '03-09': ['Sverre og Sindre', '- etter Kong Sverre, som døde denne dagen i 1202, han "som talte Roma midt imot"'],
    '03-10': ['Edel og Edle', '- etter Edel, (Ethelreda)[3] enkedronning som opprettet klosteret i Ely, England, død 679, jfr 23. juni'],
    '03-11': ['Edvin og Tale', ''],
    '03-12': ['Gregor og Gro', '- etter pave Gregor den store som døde denne dagen i 604'],
    '03-13': ['Greta og Grete', ''],
    '03-14': ['Mathilde og Mette', '- etter den hellige Mathilde, dronning gift med Henrik I av Sachsen, død denne dagen i 968'],
    '03-15': ['Christel, Christer og Chris', 'Chris ble tatt inn i revisjonen fra 1998.'],
    '03-16': ['Gudmund og Gudny', '- etter Gudmund i Holar, Gudmund Arasson, islandsk biskop som rømte til Nidaros både i 1214 og 1222.'],
    '03-17': ['Gjertrud og Trude', '- Gjertrudsdagen, Gjertrudsmesse feires, etter Gertrude av Nivelles død 664, kongsdatter og abbedisse, de reisendes og gartneres skytshelgen'],
    '03-18': ['Aleksander, Sander og Edvard', 'Sander ble tatt inn i revisjonen fra 1998. Navnedagen er etter den hellige Alexander, biskop av Jerusalem, død ca. 251, minnes ellers 16. mai'],
    '03-19': ['Josef og Josefine', '- etter den katolske minnedag for Josef, Jesu fosterfar, skytshelgen for snekkere, tømmermenn, vedhoggere samt gravere'],
    '03-20': ['Joakim og Kim', ''],
    '03-21': ['Bendik, Bengt og Bent', '- etter den hellige Benedikt av Nursia som grunnla benediktinerordenen, etter tradisjonen døde han i Monte Cassino 21. mars 547, feires 14. mars i den ortodokse kirke og 11. juli i den katolske kirke'],
    '03-22': ['Paula og Pauline', '- etter biskop Paul av Narbonne i Frankrike som døde 290'],
    '03-23': ['Gerda og Gerd', ''],
    '03-24': ['Ulrikke og Rikke', ''],
    '03-25': ['Maria, Marie og Mari', 'Marimesse. Maria Budskapsdag til minne om da engelen Gabriel fortalte Maria at hun skulle bli mor til Frelseren. Minnedagen lagt hit fordi det nå er 9 måneder til jul.'],
    '03-26': ['Gabriel og Glenn', 'Festdag for erkeengelen Gabriel'],
    '03-27': ['Rudolf og Rudi', ''],
    '03-28': ['Åsta og Åste', ''],
    '03-29': ['Jonas og Jonatan', '- etter den hellige Jonas[4] som døde som martyr i Persia år 327 under den grusomme Sjahpur II av Persia'],
    '03-30': ['Holger og Olga', ''],
    '03-31': ['Vebjørn og Vegard', ''],
    '04-01': ['Aron, Arve og Arvid', 'Aron ble tatt inn i revisjonen fra 1998.'],
    '04-02': ['Sigvard og Sivert', ''],
    '04-03': ['Gunnvald og Gunvor', ''],
    '04-04': ['Nanna, Nancy og Nina', 'Nina ble flyttet hit fra 1. juni i revisjonen fra 1998.'],
    '04-05': ['Irene, Eirin og Eiril', 'Eiril ble tatt inn i revisjonen fra 1998. Navnedagen er etter den hellige Irene som døde 304[5]'],
    '04-06': ['Åsmund og Asmund', 'Aasmund Olavsson Vinje født 6.4. 1818, derav navnedagen'],
    '04-07': ['Oddveig og Oddvin', ''],
    '04-08': ['Asle og Atle', ''],
    '04-09': ['Rannveig og Rønnaug', ''],
    '04-10': ['Ingvald og Ingveig', ''],
    '04-11': ['Ylva og Ulf', ''],
    '04-12': ['Julius og Julie', 'Navnedagen er etter pave Julius I som døde i 352'],
    '04-13': ['Asta og Astrid', ''],
    '04-14': ['Ellinor og Nora', ''],
    '04-15': ['Oda, Odin og Odd', 'Oda ble tatt inn i revisjonen fra 1998. Odd ble flyttet hit fra 4. mars. Ove ble flyttet til 30. oktober.'],
    '04-16': ['Magnus og Mons', '- etter den hellige Magnus Erlendsson. Magnus Orknøyjarl, skytshelgen for orknøyene og for fiskere, fiskehandlere, drept 16.4.1115 av sin fetter Håkon Pålsson, gravlagt i Kirkwall. Han er den eneste norske helgen med pavelig anerkjennelse.[6]'],
    '04-17': ['Elise, Else og Elsa', ''],
    '04-18': ['Eilen og Eilert', 'Navnedagen skyldes navnelikhet med den hellige Eleutherius som etter sagnet var biskop i Illyria rundt år 138 og som har katolsk minnedag idag[7]'],
    '04-19': ['Arnfinn og Arnstein', ''],
    '04-20': ['Kjellaug og Kjellrun', ''],
    '04-21': ['Jeanette og Jannike', ''],
    '04-22': ['Oddgeir og Oddny', ''],
    '04-23': ['Georg, Jørgen og Jørn', '- etter den hellige Georg, ridder i keiser Diokletians livvakt, halshugget 303, skytshelgen for England, Venezia, Genova, Portugal, Hellas, Russland og Katalonia og for soldater og speidere, hester og håndverkere, mot pest og spedalskhet, han er en av de fjorten Nødhjelperne'],
    '04-24': ['Albert og Olaug', '- etter Albertus Magnus tysk filosof og dominikanermunk død 1280, hans minnedag er nå 15. november'],
    '04-25': ['Markus og Mark', '- etter den katolske festdagen for evangelisten Markus, skytshelgen for Egypt og Venezia, for murere, bygningsarbeidere, og for fanger'],
    '04-26': ['Terese og Tea', '- etter minnedagen for den hellige Teresa av Avila død 1582 som grunnla 17 nye klostre, feires også 15. oktober'],
    '04-27': ['Charles, Charlotte og Lotte', ''],
    '04-28': ['Vivi og Vivian', '- navnedagen etter likhet med Vitalis[8], en av de tidlige kristne martyrer, pint ihjel under keiser Nero år 60'],
    '04-29': ['Toralf og Torolf', ''],
    '04-30': ['Gina og Gitte', ''],
    '05-01': ['Filip og Valborg', '- etter Walburga[9], engelsk kongsdatter som ble abbedisse i et tysk kloster, død 779 ble feiret som vernehelgen for grøde, og blandet sammen med gamle hedenske skikker til vårfeiring. Filip ble valgt etter apostelen Filip som feires både 1. mai og 3. mai'],
    '05-02': ['Åsa og Åse', ''],
    '05-03': ['Gjermund og Gøril', ''],
    '05-04': ['Monika og Mona', '- etter Monika[10], kirkefaderen Augustins mor, feires både nå og 27. august i katolsk tradisjon'],
    '05-05': ['Gudbrand og Gullborg', '- navnedag trolig med navnelikhet til Godehard av Hildesheim[11] død 1038, tysk klosterleder[12] som har katolsk minnedag idag'],
    '05-06': ['Guri og Gyri', ''],
    '05-07': ['Maia, Mai og Maiken', ''],
    '05-08': ['Åge og Åke', ''],
    '05-09': ['Kasper og Jesper', ''],
    '05-10': ['Asbjørg, Asbjørn og Espen', ''],
    '05-11': ['Magda og Malvin', ''],
    '05-12': ['Normann og Norvald', ''],
    '05-13': ['Linda, Line og Linn', 'Line ble flyttet hit fra 20. januar i revisjonen fra 1998.'],
    '05-14': ['Kristian, Kristen og Karsten', 'Navnedagen etter det som ble kalt Christiansdag i Danmark etter kongen Christian 10 som ble innsatt denne dagen i 1912'],
    '05-15': ['Hallvard og Halvor', '- etter Hallvardsmesse, ’Hallsok’: Hallvard Vebjørnsson fra Lier , St.Hallvard, er Oslos - og de forfulgtes - skytshelgen, (1020-1043), drept med pileskudd og senket i fjorden da han ville berge en gravid kvinne fra overfall'],
    '05-16': ['Sara og Siren', ''],
    '05-17': ['Harald og Ragnhild', '- valgt navnedag for Kong Olav Vs sønn og eldste datter som symbol for 17. mai.'],
    '05-18': ['Eirik, Erik og Erika', '- etter Eriksmesse: Erik Jedvardsson , Erik IX, Sveriges skytshelgen, drept i Uppsala av den danske prins Magnus i 1160'],
    '05-19': ['Torjus, Torje og Truls', 'Torje ble tatt inn i revisjonen fra 1998.'],
    '05-20': ['Bjørnar og Bjørnhild', '- etter samme navnebetydning som Bernhard, minnedag idag for den hellige Bernardin av Siena[13] død 1444, folketaler, skytshelgen for ull-vevere'],
    '05-21': ['Helene, Ellen og Eli', '- etter Helene, svensk helgen fra 1100-tallet = Elin av Skövde[14], som etter en pilegrimsreise ble myrdet på vei til kirken på grunn av falske anklager'],
    '05-22': ['Henning og Henny', '- etter biskop Henning av Åbo død 1367'],
    '05-23': ['Oddleif og Oddlaug', ''],
    '05-24': ['Ester og Iris', '- etter Ester fra Esters bok i Bibelen, dronning i Persia som befridde jødene'],
    '05-25': ['Ragna og Ragnar', ''],
    '05-26': ['Annbjørg og Annlaug', ''],
    '05-27': ['Katinka og Cato', ''],
    '05-28': ['Vilhelm, William og Willy', '- fra det gamle ’Vilhelmsføre’ Navnedagen er etter Vilhelm av Aquitania, (Vilhelm av Gellone), han kunne gå gjennom ild uten skade, da han døde 28.mai 812 ringte alle klostrets klokker av seg selv.[15]'],
    '05-29': ['Magnar og Magnhild', '- etter den tidligere navnedagen for Maximus som har samme betydning som Magn- på norrønt, Maximinus var biskop i Trier på 300-tallet, etter sagnet møtte han en bjørn på vei til Rom, roet den ned og red på den inn i byen.[16]'],
    '05-30': ['Gard og Geir', ''],
    '05-31': ['Pernille og Preben', '- etter den hellige Petronilla, pilegrimers skytshelgen[17]'],
    '06-01': ['June og Juni', 'I perioden 1989–1998 var det Nina og Njål. June ble flyttet hit fra 26. juni i revisjonen fra 1998. Nina ble flyttet til 4. april og Njål til 5. september.'],
    '06-02': ['Runa, Runar og Rune', ''],
    '06-03': ['Rasmus og Rakel', '- minnedag for Erasmus[18], også kalt Elmo - sjøfarernes skytshelgen, han var en biskop i Antiokia og ble martyr i 303, og er opphavet til St.Elms-ild, et glimt i skipets mastetopp som varslet storm på havet, man påkalte ham som vern mot uværet, han var også skytshelgen for enker og foreldreløse - i norske primstaver kalt Rasmusdagen eller Skoklefall, både 2. og 3.mai har vært brukt'],
    '06-04': ['Heidi og Heid', 'Heid ble tatt inn i revisjonen fra 1998. Heine ble flyttet til 20. oktober.'],
    '06-05': ['Torbjørg, Torbjørn og Torben', ''],
    '06-06': ['Gustav og Gyda', ''],
    '06-07': ['Robert og Robin', ''],
    '06-08': ['Renate og René', ''],
    '06-09': ['Kolbein og Kolbjørn', '- på primstaven: Kolbjørn med laksen = Columbamesse, etter Columba av Iona, Irlands og Skottlands apostel død 597, bodde i 34 år på øya i de Indre Hebridene, klostergrunnlegger, og skald som tok vare på skaldetradisjoner, Kolbjørn er den norske formen av navnet'],
    '06-10': ['Ingolf og Ingunn', ''],
    '06-11': ['Borgar, Bjørge og Bjørg', 'Borgar ble flyttet hit fra 26. oktober i revisjonen fra 1998.'],
    '06-12': ['Sigfrid, Sigrid og Siri', ''],
    '06-13': ['Tone, Tonje og Tanja', 'Tone ble flyttet hit fra 2. november i revisjonen fra 1998. Navnedagen er etter Antonius av Padua (Padova) Nasjonalhelgen for Portugal, skytshelgen for sjøfolk og fanger, avbildes med barn i armene'],
    '06-14': ['Erlend og Erland', ''],
    '06-15': ['Vigdis og Viggo', '- etter navnelikhet med Vitus, helgen som led martyrdøden under Diocletians forfølgelser. Han var en av de fjorten nødhjelpere og kunne hjelpe barn og unge mot epilepsi og kramper.'],
    '06-16': ['Torhild, Toril og Tiril', 'Tiril ble tatt inn i revisjonen fra 1998.'],
    '06-17': ['Botolv og Bodil', '- etter Botolf av Icanho (i Suffolk) død 680, lærd klostergrunnlegger i ’Botolps Town’= Boston England'],
    '06-18': ['Bjarne og Bjørn', ''],
    '06-19': ['Erling og Elling', ''],
    '06-20': ['Salve, Sølve og Sølvi', 'Salve ble tatt inn i revisjonen fra 1998. Navnedagen etter pave Sylverius død 537,[19]'],
    '06-21': ['Agnar og Annar', ''],
    '06-22': ['Håkon og Maud', '- navnedagen ble valgt fordi Kong Haakon VII og Dronning Maud denne dagen i 1906 ble kronet i Nidarosdomen'],
    '06-23': ['Elfrid og Eldrid', '- etter Ethelreda[20] enkedronning som opprettet det berømte klosteret i Ely, England, død 679, jfr 10. mars'],
    '06-24': ['Johannes, Jon og Hans', 'Jonsvaka, Jonsmesse, Sankthans: Minnedagen for Døperen Johannes, Helligdag i Sverige, og Finland. Navnene Jon og Hans er varianter av Johannes'],
    '06-25': ['Jørund og Jorunn', ''],
    '06-26': ['Jenny og Jonny', 'June ble flyttet herfra til 1. juni i revisjonen fra 1998. Navnedagen skyldes Johannes martyr[21], død 362, dagen ble feiret som helligdag like til 1772'],
    '06-27': ['Aina, Ina og Ine', 'Ine ble tatt inn i revisjonen fra 1998.'],
    '06-28': ['Lea, Leo og Leon', 'Lea ble tatt inn i revisjonen fra 1998.'],
    '06-29': ['Peter, Petter og Per', '- etter Persok på primstaven, apostelen Peters dag, feires sammen med apostelen Paulus jfr 1.august'],
    '06-30': ['Solbjørg og Solgunn', ''],
    '07-01': ['Ask og Embla', 'I perioden 1989–1998 var det Arnhild og Arnljot. Arnhild ble flyttet til 4. august og Arnljot til 1. desember.'],
    '07-02': ['Kjartan og Kjellfrid', ''],
    '07-03': ['Andrea, Andrine og André', 'Andrine ble tatt inn i revisjonen fra 1998.'],
    '07-04': ['Ulrik og Ulla', ''],
    '07-05': ['Mirjam og Mina', ''],
    '07-06': ['Torgrim og Torgunn', ''],
    '07-07': ['Håvard og Hulda', ''],
    '07-08': ['Sunniva, Synnøve og Synne', '- Seljumannamesse for St.Sunniva, Bergens skytshelgen, kom fra Irland, rømte fra hedensk tvangsgiftermål og drev i land på Selje ca. 950'],
    '07-09': ['Gøran, Jøran og Ørjan', 'Jøran ble tatt inn i revisjonen fra 1998.'],
    '07-10': ['Anita og Anja', ''],
    '07-11': ['Kjetil og Kjell', ''],
    '07-12': ['Elias og Eldar', ''],
    '07-13': ['Mildrid, Melissa og Mia', 'Melissa ble tatt inn i revisjonen fra 1998. Navnedagen er etter Mildred (Mildrida)[22], engelsk abbedisse i Minster på Isle of Thanet i Kent, død ca. 700'],
    '07-14': ['Solfrid og Solrun', ''],
    '07-15': ['Oddmund og Oddrun', ''],
    '07-16': ['Susanne og Sanna', '- etter den hellige Susanna, en martyr og helgen fra Dalmatia. Hun skal ha vært datter til den hellige Gabinus av Roma og niese til pave Caius. Hun ble halshogd i Roma i 295 under keiser Diokletian.'],
    '07-17': ['Guttorm og Gorm', ''],
    '07-18': ['Arnulf og Ørnulf', ''],
    '07-19': ['Gerhard og Gjert', ''],
    '07-20': ['Margareta, Margit og Marit', '- etter primstavens Margretemesse for Margareta av Antiokia, fødendes skytshelgen, halshugget av hærfører Olymbrias 307, hun avslo hans frieri på grunn av sin tro'],
    '07-21': ['Johanne, Janne og Jane', ''],
    '07-22': ['Malene, Malin og Mali', '#NAVN?'],
    '07-23': ['Brita, Brit og Britt', 'Britt ble tatt inn i revisjonen fra 1998. Navnedagen er etter den hellige Birgitta av Vadstena, 1303–1373, skytshelgen for Sverige og for pilegrimer, for leger og for en fredelig død, en av Europas Vernehelgener'],
    '07-24': ['Kristine, Kristin og Kristi', '- etter Kristina (Christina) av Bolsena, martyr som ungjente 304 fordi hun knuste avgudsbilder og delte ut gullet til fattige.[23]'],
    '07-25': ['Jakob, Jack og Jim', '- primstavens Jakob Våthatt, apostelen Jakob, skytshelgen for Spania som da blir til navnet Sant-iago'],
    '07-26': ['Anna, Anne og Ane', '- etter den Katolske festdag for Anna (og Joakim), jomfru Marias foreldre'],
    '07-27': ['Marita og Rita', ''],
    '07-28': ['Reidar og Reidun', ''],
    '07-29': ['Olav, Ola og Ole', 'Ole ble tatt inn i revisjonen fra 1998. Navnedagen er fra Olsok, minnedagen for Sankt Olavs død på Stiklestad i 1030'],
    '07-30': ['Aurora, Audhild og Aud', 'Aurora ble tatt inn i revisjonen fra 1998.'],
    '07-31': ['Elin og Eline', '- etter Helene, svensk helgen fra 1100-tallet = Elin av Skövde[24], som etter en pilegrimsreise ble myrdet på vei til kirken på grunn av falske anklager jfr 21. mai'],
    '08-01': ['Peder og Petra', '- etter minnedagen for apostelen Peters befrielse fra fengselet i Jerusalem, på primstaven kalt Per Vinkel, Peder Vindfell, jfr 29.juni'],
    '08-02': ['Karen og Karin', ''],
    '08-03': ['Oline, Oliver og Olve', 'Oliver ble tatt inn i revisjonen fra 1998. Men Oline og Olve er valgt fordi denne dagen er kalt \'Lille-Olsok\', vesle Olsok, da biskop Grimkjel fant St. Olavs skrin 3. aug. 1031 med Olavs kropp like frisk'],
    '08-04': ['Arnhild, Arna og Arne', 'Arnhild ble flyttet hit fra 1. juli i revisjonen fra 1998.'],
    '08-05': ['Osvald og Oskar', '- etter Oswald av Northumbria, biskop og konge i England, død 642'],
    '08-06': ['Gunnlaug og Gunnleiv', ''],
    '08-07': ['Didrik og Doris  '],
    '08-08': ['Evy og Yvonne', ''],
    '08-09': ['Ronald og Ronny', ''],
    '08-10': ['Lorents, Lars og Lasse', '- etter diakonen Sankt Laurentius’ dag, han døde 258, ble brent over en rist'],
    '08-11': ['Torvald og Tarald', ''],
    '08-12': ['Klara og Camilla', '- etter minnedagen for den hellige Klara av Assisi død 1253, hun grunnla klarissenes orden sammen med Frans av Assisi'],
    '08-13': ['Anny, Anine og Ann', 'Anine ble tatt inn i revisjonen fra 1998.'],
    '08-14': ['Hallgeir og Hallgjerd', ''],
    '08-15': ['Margot, Mary og Marielle', 'Marielle ble tatt inn i revisjonen fra 1998. Navnedagen er etter festdagen i Den katolske og den ortodokse kirke for jomfru Marias opptagelse i himmelen. På primstaven kalt Marimesse førre'],
    '08-16': ['Brynjulf og Brynhild', ''],
    '08-17': ['Verner og Wenche', ''],
    '08-18': ['Tormod og Torodd', ''],
    '08-19': ['Sigvald og Sigve', '- etter minnedagen for Sebald,[25], biskop i Trier død ca. 770, Nürnbergs skytshelgen'],
    '08-20': ['Bernhard og Bernt', '- etter Bernhard av Clairvaux død 20/8 1153 grunnla cistercienserordenen, kirkelærer, veiledet korstogsfarerne, skytshelgen for Gibraltar og Genova, for birøktere og mot dyresykdom'],
    '08-21': ['Ragnvald og Ragni', '- etter minnedagen (som egentlig er 20.aug) for den hellige Ragnvald Orknøyjarl død 1158, dikter, korstog til Jerusalem sammen med Erling Skakke, begynte byggngen av den majestetiske St.Magnus-katedralen i Kirkwall, samtidig minnedag idag for Ragnvald Brusessøn jarl over Orknøyene, fostersønn av Hellig Olav, drept 1045 av onkelen, bygget Olavskirke'],
    '08-22': ['Harriet og Harry', ''],
    '08-23': ['Signe og Signy', ''],
    '08-24': ['Belinda og Bertil', '- etter primstavens Barsok, også kalt Bardonsvoka, Berdon, Baro bukkekniv, eller Bertel Brytestrå som er festdagen til minne om apostelen Bartolomeus'],
    '08-25': ['Ludvig, Lovise og Louise', '- etter minnedgaen for Ludvig den hellige død 1270, (Ludvig IX av Frankrike) som er skytshelgen for 38 forskjellige tilfeller, han bygde blant annet universitetene i Toulouse og Sorbonne'],
    '08-26': ['Øyvind, Eivind og Even', ''],
    '08-27': ['Roald og Rolf', ''],
    '08-28': ['Artur og August', '- etter Kirkefaderen Augustin av Hippo kom fra N-Afrika, og ble døpt av Ambrosius i Milano i 387, ble en av oldtidens store teologer, død 430'],
    '08-29': ['Johan, Jone og Jo', '#NAVN?'],
    '08-30': ['Benjamin og Ben', ''],
    '08-31': ['Berta og Berte', '- etter minnedagen for Bertha fra Artois i Frankrike, som stiftet klosteret Blangy ca. år 720.[26]'],
    '09-01': ['Solveig og Solvor', ''],
    '09-02': ['Lisa, Lise og Liss', ''],
    '09-03': ['Alise, Alvhild og Vilde', 'Vilde ble tatt inn i revisjonen fra 1998.'],
    '09-04': ['Ida og Idar', '- etter den hellige Ida (Itha) av Herzfeldt,[27], «de fattiges mor», skytshelgen for gravide, død 825'],
    '09-05': ['Brede, Brian og Njål', 'Njål ble flyttet hit fra 1. juni i revisjonen fra 1998.'],
    '09-06': ['Sollaug, Siril og Siv', 'Siril ble tatt inn i revisjonen fra 1998.'],
    '09-07': ['Regine og Rose', '- etter de to helgener Regine,[28], martyr i Gallia 251 + St.Rosalia siciliansk eneboer død 4? 7? sept 1160,.[29]'],
    '09-08': ['Amalie, Alma og Allan', 'Amalie ble tatt inn i revisjonen fra 1998.'],
    '09-09': ['Trygve, Tyra og Trym', 'Trym ble tatt inn i revisjonen fra 1998.'],
    '09-10': ['Tord og Tor', ''],
    '09-11': ['Dagny og Dag', ''],
    '09-12': ['Jofrid og Jorid', ''],
    '09-13': ['Stian og Stig', ''],
    '09-14': ['Ingebjørg og Ingeborg', ''],
    '09-15': ['Aslak og Eskil', '- etter Eskil (biskop) (ca. 1100 - 1182), erkebiskop i Lund i datidens Danmark, nå i Sverige fra 1137 til 1177 og kjent som en stor kirke- og klosterbygger, hans minnedag er egentlig 6. september. Han er oppkalt etter Eskil[30] som ga navn til Eskilstuna'],
    '09-16': ['Lillian og Lilly', ''],
    '09-17': ['Hildebjørg og Hildegunn', '- etter minnedagen for Hildegard av Bingen tysk abbedisse, fikk syner, skrev sanger som er blitt ’moderne’ idag, ga ut bøker med mange visjoner, død 1179.'],
    '09-18': ['Henriette og Henry', ''],
    '09-19': ['Konstanse og Connie', '- etter den hellige Constantia,[31], drept som martyr i år 67 under keiser Nero'],
    '09-20': ['Tobias og Tage', '- Tobias, fra den apokryfe Tobits bok, varslet ødeleggelsen av Ninive i 612 f Kr.'],
    '09-21': ['Trine og Trond', ''],
    '09-22': ['Kyrre og Kåre', ''],
    '09-23': ['Snorre og Snefrid', '- Snorre Sturlason døde denne dagen i 1241'],
    '09-24': ['Jan og Jens', '- etter minnedagen for Johannes døperens unnfangelse, både Jan og Jens er varianter av Johannes'],
    '09-25': ['Ingvar og Yngvar', ''],
    '09-26': ['Einar og Endre', ''],
    '09-27': ['Dagmar og Dagrun', '- etter Dagmar av Danmark, den bøhmiske prinsesse Dragomir som ble gift med Valdemar Sejer i Danmark, kaltes der Dagmar, døde 1212 i barsel'],
    '09-28': ['Lena og Lene', ''],
    '09-29': ['Mikael, Mikal og Mikkel', '- Mikkelsmess, feiring av erkeengelen Mikael, Sankt Såle-Mikkel som ifølge Draumkvedet veier sjelene'],
    '09-30': ['Helga, Helge og Hege', '- navnene betyr hellig, navnedagen er derfor tatt etter kirkefader Hieronymus, som betyr \'hellig navn\', han døde 420'],
    '10-01': ['Rebekka og Remi', '- navnedag etter Sankt Remigius, biskop av Reims, han omvendte kong Klodvig I i 496, se Klosterkirken Saint-Remi'],
    '10-02': ['Live og Liv', ''],
    '10-03': ['Evald og Evelyn', '- Evald den lyse og Evald den mørke,[32] skytshelgener for Westfalen 600-tallet'],
    '10-04': ['Frans og Frank', '- Frans av Assisis dag, han stiftet fransiskanerordenen, død 1226, skytshelgen for fattige, for dyr - derav ’Dyrebeskyttelsens dag’ i dag'],
    '10-05': ['Brynjar, Boye og Bo', 'Boye ble tatt inn i revisjonen fra 1998.'],
    '10-06': ['Målfrid og Møyfrid', ''],
    '10-07': ['Birgitte, Birgit og Berit', '- primstavens Britemesse for Birgitta av Vadstena, død 1373, grunnla Birgittinerordenen. Sveriges skytshelgen og en av Europas Vernehelgener'],
    '10-08': ['Benedikte og Bente', ''],
    '10-09': ['Leidulf og Leif', ''],
    '10-10': ['Fridtjof, Frida og Frits', 'Frida ble tatt inn i revisjonen fra 1998. Fridtjof Nansen ble født denne dagen i 1861, og det er bakgrunn for navnedagen'],
    '10-11': ['Kevin, Kennet og Kent', 'Kevin ble tatt inn i revisjonen fra 1998.'],
    '10-12': ['Valter og Vibeke', ''],
    '10-13': ['Torgeir, Terje og Tarjei', ''],
    '10-14': ['Kaia og Kai', ''],
    '10-15': ['Hedvig og Hedda', ''],
    '10-16': ['Flemming og Finn', ''],
    '10-17': ['Marta og Marte', ''],
    '10-18': ['Kjersti og Kjerstin', ''],
    '10-19': ['Tora og Tore', ''],
    '10-20': ['Henrik, Heine og Henrikke', '- etter Henrik den hellige, Finlands apostel, biskop i Uppsala, død 1156 - Henrikke ble tatt inn i revisjonen fra 1998. Heine ble flyttet hit fra 4. juni. Hermann ble flyttet herfra til 29. januar.'],
    '10-21': ['Bergljot og Birger', ''],
    '10-22': ['Karianne, Karine og Kine', 'Karianne ble tatt inn i revisjonen fra 1998.'],
    '10-23': ['Severin og Søren', '- etter Severinus Boëtius, kristen filosof 500-t , St.Søren-dagen feires i Danmark,'],
    '10-24': ['Eilif og Eivor', ''],
    '10-25': ['Margrete, Merete og Märtha', ''],
    '10-26': ['Amandus og Amanda', 'I perioden 1989–1998 var det Borgar og Borgny. Borgar ble flyttet til 11. juni og Borgny til 2. desember. Minnedag for både Amandus av Worms biskop på 600-tallet,[33] og Amandus første biskop i Strassbourg d 355,.[34]'],
    '10-27': ['Sturla og Sture', ''],
    '10-28': ['Simon og Simen', '-på primstaven Simonsmesse, for apostelen Simon Seloten'],
    '10-29': ['Noralf og Norunn', ''],
    '10-30': ['Aksel, Ånund og Ove', 'Ove ble flyttet hit fra 15. april i revisjonen fra 1998.'],
    '10-31': ['Edit og Edna', ''],
    '11-01': ['Veslemøy og Vetle', ''],
    '11-02': ['Tove og Tuva', 'Tuva ble tatt inn i revisjonen fra 1998, og Tone ble flyttet til 13. juni.'],
    '11-03': ['Raymond og Roy', ''],
    '11-04': ['Otto og Ottar', ''],
    '11-05': ['Egil og Egon', ''],
    '11-06': ['Leonard og Lennart', '- etter Leonard(us),[35], fransk eremitt som reddet dronningens liv og ble abbed, død 560'],
    '11-07': ['Ingebrigt og Ingelin', ''],
    '11-08': ['Ingvild og Yngvild', ''],
    '11-09': ['Tordis og Teodor', '- etter Teodor,[36] romersk soldat som ble martyr 306, skytshelgen for soldater'],
    '11-10': ['Gudbjørg og Gudveig', ''],
    '11-11': ['Martin, Morten og Martine', '- Mortensmesse på primstaven, Primtegn: gås, for Martin av Tours, tiggernes og Frankrikes skytshelgen, (Helligdag i Frankrike og Belgia) – han gjemte seg i gåseflokken for å slippe å bli biskop, død 397'],
    '11-12': ['Torkjell og Torkil', '- etter Thorkild (Torkjell) biskop i Oslo død 1248'],
    '11-13': ['Kirsten og Kirsti', ''],
    '11-14': ['Fredrik, Fred og Freddy', ''],
    '11-15': ['Oddfrid og Oddvar', ''],
    '11-16': ['Edmund og Edgar', '- etter minnedagen for Edmund, skattemester og senere erkebiskop av Canterbury død 1288.'],
    '11-17': ['Hugo, Hogne og Hauk', 'Hauk ble tatt inn i revisjonen fra 1998.'],
    '11-18': ['Magne og Magny', ''],
    '11-19': ['Elisabeth og Lisbet', '- Navnedagen er etter den hellige Elisabeth av Ungarn, hennes dødsdag i 1231 var 17. november men feires også den 19., dagen da hun ble begravet. Hun ble bare 24 år gammel, men ble saligkåret allerede to år etter'],
    '11-20': ['Halvdan og Helle', ''],
    '11-21': ['Mariann og Marianne', '- navnevalg etter primstavens Marioffer, jomfru Marias fremstilling i tempelet'],
    '11-22': ['Cecilie, Silje og Sissel', '- eter St. Cecilia (Cæcilia), martyr år 230, ble halshugget 3 ganger og så skoldet, døde etter 3 dager.. (kirke-)musikkens skytshelgen.'],
    '11-23': ['Klement og Klaus', '- primstavens Klementsmesse, for pave Klemens I som ble druknet i Svartehavet ved Krim ca. år 100.'],
    '11-24': ['Gudrun og Guro', ''],
    '11-25': ['Katarina, Katrine og Kari', '- primstavens Karimesse, (Kari med rokken, Kari Vaskar) for Katarina av Alexandria lagt på hjul og steile og halshogd 304, en av de fire hovedjomfruer, filosofers og læreres skytshelgen'],
    '11-26': ['Konrad og Kurt', '- etter den hellige Konrad avKonstanz,[37], biskop død 975'],
    '11-27': ['Torlaug og Torleif', ''],
    '11-28': ['Ruben og Rut', ''],
    '11-29': ['Sofie og Sonja', ''],
    '11-30': ['Andreas og Anders', '- fra primstavens Andreasmesse, for apostelen Andreas, Primtegn:skjevt kors, på engelsk: Andrew, skytshelgen for Skottland, og Russland'],
    '12-01': ['Arnold, Arnljot og Arnt', 'Arnljot ble flyttet hit fra 1. juli i revisjonen fra 1998. Navnedagen er etter fransiskanermunken Arnold som dro ut i 1303 som misjonær til Kina[38]'],
    '12-02': ['Borghild, Borgny og Bård', 'Borgny ble flyttet hit fra 26. oktober i revisjonen fra 1998.'],
    '12-03': ['Sveinung og Svein', ''],
    '12-04': ['Barbara og Barbro', '- Navnedagen er etter den gamle Barbromesse, minnedag for Barbara fra Nikomedia død ca. år 300, hun ble stengt inne i et tårn av faren, og ble martyr, samme dag ble faren drept av lyn, hun er blitt skytshelgen for gruvefolk og artilleri, og mot feber. På de gamle primstaver avmerket med et tårn'],
    '12-05': ['Stine og Ståle', ''],
    '12-06': ['Nils og Nikolai', '- Navnedagen er etter den hellige biskop Nikolaus av Myra Sankt Nikolas, opphavet til Santa Claus og vår julenisse'],
    '12-07': ['Hallfrid og Hallstein', ''],
    '12-08': ['Marlene, Marion og Morgan', 'Marlene ble tatt inn i revisjonen fra 1998. Forøvrig er navnedagen etter den katolske festdagen for Den ubesmittede unnfangelse av jomfru Maria, helligdag i mange katolske land'],
    '12-09': ['Anniken og Annette', '- etter Anna, Jesu mor, Anna matris Mariae, på primstaven: Annadagen, Anna røytrauv'],
    '12-10': ['Judit og Jytte', 'Navnedagen er etter festdagen for jødiske Judit omtalt i Judits bok, hun drepte den assyriske hærføreren og befridde jødene.'],
    '12-11': ['Daniel og Dan', ''],
    '12-12': ['Pia og Peggy', ''],
    '12-13': ['Lucia og Lydia', 'Luciadagen etter etter Lucia fra Syrakus på Sicilia, brent på bålet år 304, 18 år gammel.'],
    '12-14': ['Steinar og Stein', ''],
    '12-15': ['Hilda og Hilde', 'Navnedagen er til minne om Hilde av Northumberland som 13 år gammel ble kristen sammen med sin onkel, kong Edwin av Northumbria. Senere grunnla hun klosteret i Whitby, der hun levde til sin død ca. år 620.'],
    '12-16': ['Oddbjørg og Oddbjørn', ''],
    '12-17': ['Inga og Inge', ''],
    '12-18': ['Kristoffer og Kate', '- Navnedagen er etter St. Kristoffer, som har katolsk minnedag både 25. juli og 18. desember. Navnet fikk han fordi ha etter legenden bar Kristus over en elv i form av et lite barn. Han er en av de fjorten nødhjelpere'],
    '12-19': ['Iselin og Isak', ''],
    '12-20': ['Abraham og Amund', '- etter den syriske munken Abraham,[39] som ble biskop i Kratia Bithynia (Tyrkia idag).'],
    '12-21': ['Tomas og Tom og Tommy', 'Primstavens Tomasmesse etter apostelen Tomas'],
    '12-22': ['Ingemar og Ingar', ''],
    '12-23': ['Sigurd og Sjur', '- primstavens Sjursmesse eller Tollesmesse, etter den islandske biskop Sankt Thorlákr Thorhallsson'],
    '12-24': ['Adam og Eva', ''],
    '12-25': [' Ingen navnedag – Første juledag'],
    '12-26': ['Stefan og Steffen', 'Navnedagen er etter den hellige Stefanus, kirkens første martyr'],
    '12-27': ['Narve og Natalie', ''],
    '12-28': ['Unni, Une og Unn', 'Une ble tatt inn i revisjonen fra 1998.'],
    '12-29': ['Vidar og Vemund', ''],
    '12-30': ['David, Diana og Dina', 'Dina ble tatt inn i revisjonen fra 1998.'],
    '12-31': ['Sylfest, Sylvia og Sylvi', '- etter pave Silvester I.(Sylvester) som innviet Peterskirken, dette er hans dødsdag i år 335 og i mange europeiske land kalles denne dag derfor ’Silvesteraften’ , i Norge ’Sylfestkvelden’']}

Class = Navnedag
